name: 'Matter Switch for Hager - After rebase'
packageKey: 'matter-switch-for-hag'
permissions:
  matter: {}
description: "Dynamic changes applied. Always on not working"
vendorSupportInformation: "https://support.smartthings.com"
